name: deploy dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::584725262483:role/GithubActions
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      - name: export environment variables
        run : npm run dotEnv

      - name: seed db
        run: npm run seed

      - name: run integration test
        run: npm run test

      - name: deploy to test environment
        run: npx sls deploy -s ci-environment

      - name: run acceptance tests
        run: npm run acceptance

      - name: delete test environment
        run: npx sls remove -s ci-environment

      - name: deploy to dev
        run: npx sls deploy